#!/bin/bash

# ==============================================================================
# IRCTC GMM Digital Twin Comparison Batch Script
# ==============================================================================

# Define the paths to your Original Baseline models.
# EDIT THESE PATHS to match the actual .pkl files generated from your real PCAPs.
declare -A BASELINES
BASELINES=(
    ["ips"]="/home/mayank/Desktop/IRCTC/IRCTC-Simulator/docs/Code/3/3_model_mode1.pkl"
    ["adc"]="/home/mayank/Desktop/IRCTC/IRCTC-Simulator/docs/Code/6-7/6-7_model_mode1.pkl"
    ["waf"]="/home/mayank/Desktop/IRCTC/IRCTC-Simulator/docs/Code/8-9/8-9_model_mode2.pkl"
    ["web"]="/home/mayank/Desktop/IRCTC/IRCTC-Simulator/docs/Code/10/10_model_mode2.pkl"
    ["fw2"]="/home/mayank/Desktop/IRCTC/IRCTC-Simulator/docs/Code/11/11_model_mode2.pkl"
    ["app"]="/home/mayank/Desktop/IRCTC/IRCTC-Simulator/docs/Code/12/12_model_mode2.pkl" # As seen in your previous graph
)

# Define the paths to your Emulated models.
# These paths match the output structure generated by your full_gmm.py script.
declare -A EMULATED
EMULATED=(
    ["ips"]="/home/mayank/Desktop/IRCTC/IRCTC-Simulator/docs/Mininet/Post_Simulation/ips/ips_model_mode1.pkl"
    ["adc"]="/home/mayank/Desktop/IRCTC/IRCTC-Simulator/docs/Mininet/Post_Simulation/adc1/adc1_model_mode1.pkl"
    ["waf"]="/home/mayank/Desktop/IRCTC/IRCTC-Simulator/docs/Mininet/Post_Simulation/waf1/waf1_model_mode2.pkl"
    ["web"]="/home/mayank/Desktop/IRCTC/IRCTC-Simulator/docs/Mininet/Post_Simulation/web/web_model_mode2.pkl"
    ["fw2"]="/home/mayank/Desktop/IRCTC/IRCTC-Simulator/docs/Mininet/Post_Simulation/fw2/fw2_model_mode2.pkl"
    ["app"]="/home/mayank/Desktop/IRCTC/IRCTC-Simulator/docs/Mininet/Post_Simulation/app/app_model_mode2.pkl"
)

# Ordered list of nodes for a logical pipeline output
NODES=("ips" "adc" "waf" "web" "fw2" "app")

echo "============================================================"
echo " Starting Automated GMM Comparison Batch Job"
echo "============================================================"

for node in "${NODES[@]}"; do
    baseline_file="${BASELINES[$node]}"
    emulated_file="${EMULATED[$node]}"
    
    echo ""
    echo "[*] --------------------------------------------------------"
    echo "[*] Analyzing Node: $(echo $node | tr '[:lower:]' '[:upper:]')"
    echo "[*] --------------------------------------------------------"

    # Check if baseline model exists
    if [[ ! -f "$baseline_file" ]]; then
        echo "[!] Error: Missing baseline model -> $baseline_file"
        echo "    Skipping $node..."
        continue
    fi

    # Check if emulated model exists
    if [[ ! -f "$emulated_file" ]]; then
        echo "[!] Error: Missing emulated model -> $emulated_file"
        echo "    Skipping $node..."
        continue
    fi

    # Execute the Python comparison script
    python3 compare_gmm.py "$baseline_file" "$emulated_file"

done

echo ""
echo "============================================================"
echo " [+] Batch comparison complete!"
echo "============================================================"